version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - "/helm/gke/business-dev/**/*"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 8
    groups:
      providers:
        patterns:
          - "provider*"
      modules:
        patterns:
          - "module*"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "terraform"
    directories:
      - "/helm/gke/business-prod/**/*"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/New_York"
    groups:
      business-prod-dependencies:
        patterns:
          - "hashicorp/*"
          - "grafana/grafana"
      modules:
        patterns:
          - "terraform-google-modules/*"
    ignore:
      - dependency-name: "hashicorp/vault"
        versions: '>= 4'
        update-types: ["version-update:semver-major"]
      - dependency-name: "grafana/grafana"
        versions: '>= 3'
    open-pull-requests-limit: 6

  - package-ecosystem: "terraform"
    directories:
      - "/helm/gke/business-stg/**/*"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    groups:
      providers:
        patterns:
          - "hashicorp/*"
      modules:
        patterns:
          - "module*"
    allow:
      - dependency-type: "all"
